# Basic
title: Lp NAL
# subtitle: A blog-orientation theme for Jekyll
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 一个CTFer的随笔和杂谈
creator: <a href="http://blog.lpnal.me">@asp3n</a>

url: "http://blog.lpnal.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: lpnal
    # duoshuo: 
    
# Social
social:
    # weibo: lpnal
    github: ultranal
    # twitter: ultranal
    # gplus: 107108267983477358170
    mail: ultranal@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
